name: Run PHPUnit tests

on:
    workflow_call:
        inputs:
            php-version-matrix:
                description: PHP versions used in matrix
                required: false
                default: '["8.1", "8.2"]'
                type: string
            php-version-lowest:
                description: PHP version for testing lowest deps
                required: false
                default: 8.1
                type: string
            phpunit:
                description: PHPUnit script (phpunit/simple-phpunit)
                required: false
                default: phpunit
                type: string

jobs:
    phpunit:
        name: PHP ${{ matrix.php-version }}, ${{ matrix.dependency-versions }} deps, ${{ matrix.composer-options }}
        runs-on: ubuntu-latest

        strategy:
            fail-fast: false
            matrix:
                # normal, highest, non-dev installs
                php-version: ${{ fromJSON(inputs.php-version-matrix) }}
                dependency-versions: [highest]
                composer-options: [--prefer-stable]
                include:
                    # testing lowest PHP version with the lowest dependencies
                    - php-version: ${{ inputs.php-version-lowest }}
                      dependency-versions: lowest
                      composer-options: --prefer-lowest

                    # testing dev versions with the highest PHP
                    - php-version: 8.2
                      dependency-versions: highest
                      composer-options: '' # allow dev deps

        steps:
            - name: Checkout code
              uses: actions/checkout@v3

            - name: Setup PHP
              uses: shivammathur/setup-php@v2
              with:
                  coverage: none
                  php-version: ${{ matrix.php-version }}

            - name: Install Composer dependencies
              uses: ramsey/composer-install@v2
              with:
                  dependency-versions: ${{ matrix.dependency-versions }}
                  composer-options: ${{ matrix.composer-options }} --prefer-dist

            - name: Unit Tests
              run: vendor/bin/simple-phpunit -c $GITHUB_WORKSPACE/phpunit.xml.dist --testsuite unit

            - name: Functional Tests
              run: vendor/bin/simple-phpunit -c $GITHUB_WORKSPACE/phpunit.xml.dist --testsuite functional

            - name: Integration Tests
              run: vendor/bin/simple-phpunit -c $GITHUB_WORKSPACE/phpunit.xml.dist --testsuite integration

            - name: Acceptance Tests
              run: vendor/bin/simple-phpunit -c $GITHUB_WORKSPACE/phpunit.xml.dist --testsuite acceptance
