name: Check for errors with Psalm static analysis tool

on:
    workflow_call:
        inputs:
            php:
                description: PHP Version to use
                default: 8.2
                required: false
                type: string

jobs:
    psalm:
        name: Psalm
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v3

            - name: Setup PHP
              uses: shivammathur/setup-php@v2
              with:
                  php-version: ${{ inputs.php }}
                  tools: psalm:4

            - name: Install Composer dependencies
              run: composer install --no-progress --prefer-dist --optimize-autoloader

            - name: Run Psalm
              # TODO Probably --php-version should be replaced with 8.2 ?
              run: psalm --output-format=github --php-version=8.0 -c $GITHUB_WORKSPACE/psalm.xml
